# Scala ----------
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'gre/play2vim'
on_ft = ['conf', 'twirl', 'routes']
on_source = ['vim-scala']

# Typescript, Javascript ----------
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript', 'typescriptreact', 'javascriptreact']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['javascript', 'typescript', 'typescriptreact', 'javascriptreact']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'typescript', 'typescriptreact', 'javascriptreact']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'typescript', 'typescriptreact', 'javascriptreact']
hook_post_source = '''
  source ~/.vim/vimrcs/typescript.vim
'''

# HTML, CSS,etc ----------
# pug syntax
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['previm', 'tabular']
on_ft = ['md', 'mkd']
hook_add = '''
  source ~/.vim/vimrcs/markdown.vim
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_source = 'vim-markdown'
on_ft = ['md', 'mkd']

# md previewには以下を使いたい
# https://github.com/iamcco/markdown-preview.nvim

# uml
[[plugins]]
repo = 'skanehira/preview-uml.vim'
on_ft = ['uml']
hook_add = '''
  source ~/.vim/vimrcs/preview-uml.vim
'''

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']


[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['ruby', 'slim']

# Golang ----------
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
  source ~/.vim/vimrcs/go-import.vim
'''

