# [dein.toml]

[[plugins]]
repo = 'Shougo/dein.vim'

# NERDTred ----------
[[plugins]]
repo = 'scrooloose/nerdtree'
depends =['vim-nerdtree-tabs', 'nerdtree-git-plugin']
hook_add = '''
  source ~/.vim/vimrcs/nerdtree.vim
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
on_source = ['nerdtree']
hook_add = '''
  source ~/.vim/vimrcs/nerdtree.vim
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# Git ----------
# vimで差分(+, -)を左側に表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Airline ----------
[[plugins]]
repo = 'vim-airline/vim-airline'

# ColorSheme ----------
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  source ~/.vim/vimrcs/onedark.vim
'''

# Common Editor ----------
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_i = 1

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_i = 1

[[plugins]]
repo = 'kana/vim-operator-user'
on_source = ['vim-vim-operator-surround']

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']
hook_add = '''
  source ~/.vim/vimrcs/surround.vim
'''

# fzf ----------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  source ~/dotfiles/.vim/vimrcs/fzf.vim
'''

# auto complete ----------
# deopleteからcoc + lspに移行
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = '''
  source ~/.vim/vimrcs/coc.vim
'''
