# [dein.toml]
[[plugins]]
repo = 'Shougo/dein.vim'

# NERDTred ----------
[[plugins]]
repo = 'scrooloose/nerdtree'
depends =['vim-nerdtree-tabs', 'nerdtree-git-plugin']
hook_add = '''
  source ~/.vim/vimrcs/nerdtree.vim
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
on_source = ['nerdtree']
hook_add = '''
  source ~/.vim/vimrcs/nerdtree.vim
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# Git ----------
# vimで差分(+, -)を左側に表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Airline ----------
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  source ~/.vim/vimrcs/airline.vim
'''

# ColorSheme ----------
[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
augroup MyVimrc
  autocmd VimEnter * nested colorscheme hybrid
augroup End
'''

# Common Editor ----------
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_i = 1

# fzf ----------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  source ~/dotfiles/.vim/vimrcs/fzf.vim
'''

# auto complete ----------
# deopleteからcoc + lspに移行
[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'yarn install --frozen-lockfile'
hook_add = '''
  source ~/.vim/vimrcs/coc.vim
'''

# indent ------------
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  source ~/.vim/vimrcs/indent_guide.vim
'''

