# Scala ----------
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'gre/play2vim'
on_ft = ['conf', 'twirl', 'routes']
on_source = ['vim-scala']

# Typescript, Javascript ----------
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'othree/yajs'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'typescript']
hook_post_source = '''
  source ~/.vim/vimrcs/typescript.vim
'''

# HTML, CSS,etc ----------
# pug syntax
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['previm', 'tabular']
on_ft = ['md', 'mkd']
hook_add = '''
  source ~/.vim/vimrcs/markdown.vim
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_source = 'vim-markdown'
on_ft = ['md', 'mkd']

# md previewには以下を使いたい
# https://github.com/iamcco/markdown-preview.nvim

# uml
[[plugins]]
repo = 'skanehira/preview-uml.vim'
on_ft = ['uml']
hook_add = '''
  source ~/.vim/vimrcs/preview-uml.vim
'''

# ruby
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']


# Scala ----------
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
  source ~/.vim/vimrcs/go-import.vim
'''

