# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['previm', 'tabular']
on_ft = ['md', 'mkd']
hook_add = '''
  source ~/.vim/vimrcs/markdown.vim
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_source = 'vim-markdown'
on_ft = ['md', 'mkd']

# md previewには以下を使いたい
# https://github.com/iamcco/markdown-preview.nvim

# uml
[[plugins]]
repo = 'skanehira/preview-uml.vim'
on_ft = ['uml']
hook_add = '''
  source ~/.vim/vimrcs/preview-uml.vim
'''

# Golang ----------
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
  source ~/.vim/vimrcs/go-import.vim
'''

# test tool -----------
[[plugins]]
repo = 'vim-test/vim-test'
on_ft = ['go']
hook_add = '''
  source ~/.vim/vimrcs/vim-test.vim
'''

[[plugins]]
repo = 'buoto/gotests-vim'
on_ft = ['go']
hook_add = '''
  source ~/.vim/vimrcs/gotests-vim.vim
'''


