# Finder ----------
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.vim/vimrcs/denite.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.vim']

# Terminal ----------
[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  source ~/.vim/vimrcs/neoterm.vim
'''


