# Complete ----------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('python3')"
depends = ['neco-syntax', 'phpcd.vim']
on_i = 1
hook_add = '''
  source ~/.vim/vimrcs/deoplete.vim
'''

# syntax
[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1
on_souce = ['deoplete.nvim']

# PHP ----------
[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = 'php'
on_i = 1
on_souce = ['deoplete.nvim']


# Finder ----------
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.vim/vimrcs/denite.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.vim']

# Terminal ----------
[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  source ~/.vim/vimrcs/neoterm.vim
'''

