# Complete ----------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['neco-syntax', 'phpcd.vim']
on_i = 1
hook_source = '''
  source ~/.vim/vimrcs/deoplete.vim
'''

# Filer ----------
[[plugins]]
repo = 'Shougo/denite.nvim'

# syntax
[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

# PHP ----------
[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = 'php'
on_i = 1
on_souce = ['deoplete.nvim']
