# Finder ----------
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.vim/vimrcs/denite.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.vim']

# Terminal ----------
[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  source ~/.vim/vimrcs/neoterm.vim
'''

# deopleteからcoc + lspに移行
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = '''
  source ~/.vim/vimrcs/coc.vim
'''
